### ISSUE TITLE
Disable fullscreen after publish

### ISSUE THREAD

**Issue by brhoomjs** [flashphoner/flashphoner_client#17]
I'm wondering if I can prevent going fullscreen after publishing stream.

Using Safari & Webkit. Via angular

Thanks

**Comment by flashphoner** [comment]
Please check if this is reproducing in [Two Way Streaming](https://github.com/flashphoner/flashphoner_client/tree/wcs_api-2.0/examples/demo/streaming/two_way_streaming) example.
Please also make sure that you're using `playFisrtVideo()` function when publishing or playing in iOS Safari:
```
        if (Browser.isSafariWebRTC()) {
            Flashphoner.playFirstVideo(localVideo, true, PRELOADER_URL).then(function() {
                publishStream();
            });
            return;
        }
```

**Comment by brhoomjs** [comment]
Thanks for your response 
I'm using this method "One Streamer To Many Consumers"

This happen only for publisher
```				
const s = session.createStream({
			name: "CustomStream",
			mediaProvider: "WebRTC",
			constraints: { video: true, audio: true },
			//@ts-ignore
			display,
		});
s.on("PUBLISHING", (str: FP.Stream) => {
	resolve(str);
}).publish();
```

**Comment by flashphoner** [comment]
You should wrap this code in `Flashphoner.playFirstVideo()` as shown [above](https://github.com/flashphoner/flashphoner_client/issues/17#issuecomment-1005353915)

**Comment by brhoomjs** [comment]
Alright got it, Thanks for helping out.
